name: Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version 🚀
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
        - 5.3
        - 5.4
    container:
      image: swift:${{ matrix.swift }}
    steps:
    - uses: actions/checkout@v2
    - run: swift build

  lint:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode:
          - '12.0'
          - '12.4'
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    - uses: actions/checkout@v2
    - run: pod lib lint --fail-fast

  create-release:
    runs-on: ubuntu-latest
    needs: [lint, build]
    steps:
    - uses: actions/checkout@v2
    - uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.JAZZY_PAT }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: ${{ github.event.inputs.version }}
